openapi: 3.0.0
info:
  title: Social Network API
  version: 1.0.0
  # components:
  # securitySchemes:
  #   bearerAuth:
  #     type: http
  #     scheme: bearer
  #     bearerFormat: JWT
  description: Documentation for Social Network API

components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT

servers:
  - url: http://localhost:3001/api
    description: Local server

paths:
